### ISSUE TITLE
install  error

### ISSUE THREAD

**Issue by bibs0n** [tkanarsky/homebridge-alarm-listener#2]
runnng homebrisge on raspian, installing package gives me this error
pi@homebridge:/var/lib/homebridge $ npm install homebridge-alarm-listener@2.0.0
npm WARN saveError ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No README data
npm WARN homebridge No license field.

+ homebridge-alarm-listener@2.0.0
updated 1 package and audited 252 packages in 4.398s

9 packages are looking for funding
  run `npm fund` for details

found 25 vulnerabilities (9 low, 16 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@homebridge:/var/lib/homebridge $

**Comment by tkanarsky** [comment]
NPM's complaining that there's no package currently instantiated in the current working directory. I think plugins are supposed to be installed globally with `npm install -g` instead of `npm install`.

Try first uninstalling the plugin from the local directory with `npm uninstall homebridge-alarm-listener`, and then installing globally with `npm install -g homebridge-alarm-listener`.

**Comment by bibs0n** [comment]
here is the log after doing above
pi@homebridge:/var/lib/homebridge $ npm uninstall homebridge-alarm-listener
npm WARN saveError ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No README data
npm WARN homebridge No license field.

removed 1 package and audited 232 packages in 4.738s

9 packages are looking for funding
  run `npm fund` for details

found 19 vulnerabilities (7 low, 12 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@homebridge:/var/lib/homebridge $ npm install -g homebridge-alarm-listener
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-05-02T07_42_39_549Z-debug.log
pi@homebridge:/var/lib/homebridge $

**Comment by bibs0n** [comment]
got it installed how and onto homekit, can you give me a little more info on the"mic_device" field, i have run arecord -L to get a list of all recording devices and here is my log
pi@homebridge:/var/lib/homebridge $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=Device
    USB PnP Sound Device, USB Audio
    Default Audio Device
sysdefault:CARD=Device
    USB PnP Sound Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct sample mixing device
dsnoop:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct sample snooping device
hw:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Hardware device with all software conversions

**Comment by bibs0n** [comment]
got it working now thanks
