### ISSUE TITLE
Getting started questions

### ISSUE THREAD

**Issue by codyc1515** [tkanarsky/homebridge-alarm-listener#4]
I purchased a cheap ($6) USB microphone to use for this project, however it seems like some set-up is required if you haven't used the microphone before. I am using the official Homebridge image on a Raspberry Pi 4. Any ideas how to set-up from fresh (other than the config)? I tried using the test function on my smoke alarm to trigger it a few times but there was no indication that this was working.

**Comment by joshspicer** [comment]
To see if your microphone is working you can do something like:

```
arecord -D plughw:1,0 test.wav
```

with `plughw:1,0` equal to your device's ID.  You can then copy that file over to your computer to see if the microphone is picking up noise.

**Comment by codyc1515** [comment]
Yes I can hear my voice through there after configuring using `alsamixer`, however the background noise is quite strong. Not entirely sure what the issue is.

**Comment by codyc1515** [comment]
Looks like this project is abandoned. Closing.
